server:
  port: 8070
spring:
  application:
    name: "queries"
  config:
    import: "optional:configserver:http://localhost:8071/"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
  cloud:
#    function:
#      definition: sendEmailToUsers
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
        sendEmailToUsers-in-0:
          destination: communication-sent
          group: ${spring.application.name}
  mail:
    username: aditisingh27022002@gmail.com
    host: smtp.gmail.com
    port: 587
    password: "nvsy uott dchm akuv"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:3000/eureka/"

info:
  app:
    name: "Query Microservice"
    description: "Query Microservice for LMS"
    version: "1.0.0"



