apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-deployment
  labels:
    app: enrollment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment
  template:
    metadata:
      labels:
        app: enrollment
    spec:
      containers:
      - name: cards
        image: aditikumari823/enrollment:2.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: lms-configmap
              key: ENROLLMENTS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: lms-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: lms-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: lms-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment
spec:
  selector:
    app: enrollment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
