apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries-deployment
  labels:
    app: queries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queries
  template:
    metadata:
      labels:
        app: queries
    spec:
      containers:
      - name: cards
        image: aditikumari823/queries:2.0.0
        ports:
        - containerPort: 8070
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: lms-configmap
              key: QUERIES_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: lms-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: lms-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: lms-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: queries
spec:
  selector:
    app: queries
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
